// Generated by CoffeeScript 1.3.3
(function() {
  var log, sockjs, sockjs_url;

  sockjs = window.sockjs;

  log = function(m) {
    $('#output').append($("<code>").text(m));
    $('#output').append($("<br>"));
    return $('#output').scrollTop($('#output').scrollTop() + 10000);
  };

  sockjs_url = '/echo';

  sockjs = new SockJS(sockjs_url);

  sockjs.onopen = function() {
    return log(' [*] Connected (using: ' + sockjs.protocol + ')');
  };

  sockjs.onclose = function(e) {
    return log(' [*] Disconnected (' + e.status + ' ' + e.reason + ')');
  };

  sockjs.onmessage = function(e) {
    return log(' [ ] received: ' + JSON.stringify(e.data));
  };

  'setInterval( () -> \n  if not sockjs.readyState == SockJS.OPEN\n    l += \' (error, connection not established)\'\n  else\n    console.log(5)\n    sockjs.send({a:5})\n1000)';


  $('#input').focus();

  $('#form').submit(function() {
    var l, val;
    val = $('#input').val();
    $('#input').val('');
    l = ' [ ] sending: ' + JSON.stringify(val);
    if (!sockjs.readyState === SockJS.OPEN) {
      l += ' (error, connection not established)';
    } else {
      console.log(val);
      sockjs.send(val);
    }
    log(l);
    return false;
  });

}).call(this);
